name: firstworkflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "hello world"
      - name: goodbye
        run: echo "good bye"
